// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/98b3d3dc0a2bd8060591d39b55bba801f77dbbc7/falcor-express/falcor-express.d.ts
// Type definitions for falcor-express 0.1.2
// Project: https://github.com/Netflix/falcor-express
// Definitions by: Quramy <https://github.com/Quramy/>
// Definitions: https://github.com/borisyankov/DefinitelyTyped


declare module 'falcor-express' {
    import {Request, Response, Handler} from 'express';
    import {DataSource} from 'falcor';
    function dataSourceRoute(getDataSource: (req: Request, res: Response) => DataSource): Handler;
}