// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/98b3d3dc0a2bd8060591d39b55bba801f77dbbc7/falcor-http-datasource/falcor-http-datasource.d.ts
// Type definitions for falcor-http-datasource 0.1.3
// Project: https://github.com/Netflix/falcor-http-datasource
// Definitions by: Quramy <https://github.com/Quramy/>
// Definitions: https://github.com/borisyankov/DefinitelyTyped


declare namespace FalcorHttpDataSource {

    /**
     * A HttpDataSource object is a {@link DataSource} can be used to retrieve data from a remote JSONGraph object using the browser's XMLHttpRequest.
     **/
    class XMlHttpSource extends FalcorModel.DataSource {
        constructor(jsonGraphUrl: string);
    }
}

declare module 'falcor-http-datasource' {
    import XMlHttpSource = FalcorHttpDataSource.XMlHttpSource;
    export {XMlHttpSource};
    export default XMlHttpSource;
}