export const LOAD_EVENTS_REQUEST = 'LOAD_EVENTS_REQUEST';
export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
export const LOAD_EVENTS_FAILURE = 'LOAD_EVENTS_FAILURE';

export const LOAD_TOURNAMENT_REQUEST = 'LOAD_TOURNAMENT_REQUEST';
export const LOAD_TOURNAMENT_SUCCESS = 'LOAD_TOURNAMENT_SUCCESS';
export const LOAD_TOURNAMENT_FAILURE = 'LOAD_TOURNAMENT_FAILURE';

export const EDIT_EVENT_REQUEST = 'EDIT_EVENT_REQUEST';
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS';
export const EDIT_EVENT_FAILURE = 'EDIT_EVENT_FAILURE';